[package]
name = "spin-factor"
version = "0.1.0"
edition = "2021"

[dependencies]
spin-factor-derive = { path = "derive" }
ref-cast = "1.0"
wasmtime = { version = "18.0.2", features = ["component-model"] }
wasmtime-wasi = { version = "18.0.2", features = ["tokio"] }
wasmtime-wasi-http = "18.0.2"

[workspace]
members = ["derive"]