[package]
name = "spin-factors-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
expander = ["dep:expander"]

[dependencies]
expander = { version = "2.1.0", optional = true }
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = "2.0.52"