[package]
name = "outbound-networking-factor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
wasmtime-wasi = { workspace = true }

spin-factors = { path = "../.." }
wasi-factor = { path = "../wasi-factor" }